/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Marker } from "../src/components";
import { FaMapMarkerAlt } from "react-icons/fa";

const Earth = (props) => {
  const { nodes, materials } = useGLTF("/earth.gltf");
  return (
    <group
      rotation={[0, -0.4, 0]}
      position={[0, 0, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
        scale={1.5}
      >
        <group position={[0.0, -0.4, 1]} scale={0.5}>
          <Marker rotation={[0, Math.PI / 2, Math.PI / 2]}>
            <div
              style={{
                position: "absolute",
                fontSize: 5,
                letterSpacing: -0.2,
                left: 17.5,
              }}
            >
              Origin
            </div>
            <FaMapMarkerAlt style={{ color: "#2E6BDA" }} />
          </Marker>
        </group>
      </mesh>
    </group>
  );
};

useGLTF.preload("/earth.gltf");

export default Earth;
