/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React from "react";
import { useGLTF, Html } from "@react-three/drei";
import { Marker } from "../src/components";
import useMarkerStore from "../src/stores/marker";
import * as THREE from "three";

const Earth = (props) => {
  const { nodes, materials } = useGLTF("/earth.gltf");
  const activateColombia = useMarkerStore((state) => state.activateColombia);

  return (
    <group position={[0, 0, 0]} rotation={[0, 0, 0]} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
        scale={1}
      ></mesh>
      <Marker color="#406AFF" text="colombia" />
      <Marker color="red" text="canada" />
      <axesHelper args={[5]} />

      <Html
        style={{
          display: "flex",
          justifyContent: "end",
          alignItems: "flex-end",
          flexDirection: "column",
          padding: "1rem",
          gap: "1rem",
        }}
        fullscreen
      >
        <button className="btn font-semibold text-secondary m-4">
          Where in Canada?
        </button>
        <button
          className="btn font-semibold text-secondary m-4"
          onClick={activateColombia}
        >
          Origin
        </button>
      </Html>
    </group>
  );
};

useGLTF.preload("/earth.gltf");

export default Earth;
